server:
  error:
    include-stacktrace: on_param
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/anime?useSSL=false&createDataBaseIfNotExists=true&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update

  flyway:
    check-location: false
    locations: filesystem:/path/to/file/anywhere/on/the/filesystem

